# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['truely_dual_join.py'],
    pathex=[],
    binaries=[],
    datas=[('config.py', '.')],  # Include config.py in the bundle
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtWidgets', 
        'PyQt6.QtGui',
        'psutil',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support',
        'selenium.webdriver.support.expected_conditions',
        'webdriver_manager',
        'webdriver_manager.chrome',
        'urllib.parse',
        'hashlib',
        'logging',
        'threading',
        'platform',
        'subprocess',
        'webbrowser',
        'time',
        'datetime',
        'signal',
        'atexit',
        'os',
        'sys'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['hook-disable-location.py'],  # Add our custom runtime hook
    excludes=[
        # Completely exclude all Qt location services
        'PyQt6.QtLocation',
        'PyQt6.QtPositioning',
        'PyQt6.QtWebEngine',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtWebEngineWidgets',
        'PyQt6.QtMultimedia',
        'PyQt6.QtMultimediaWidgets',
        'PyQt6.QtBluetooth',
        'PyQt6.QtNfc',
        'PyQt6.QtSensors',
        'PyQt6.QtSerialPort',
        'PyQt6.QtSql',
        'PyQt6.QtTest',
        'PyQt6.QtXml',
        'PyQt6.QtXmlPatterns',
        'PyQt6.QtHelp',
        'PyQt6.QtDesigner',
        'PyQt6.QtUiTools',
        'PyQt6.QtOpenGL',
        'PyQt6.QtOpenGLWidgets',
        'PyQt6.QtQuick',
        'PyQt6.QtQuickWidgets',
        'PyQt6.QtQml',
        'PyQt6.QtNetwork',
        'PyQt6.QtDBus',
        # Exclude specific location-related modules
        'PyQt6.QtCore.QtLocation',
        'PyQt6.QtCore.QtPositioning',
        'PyQt6.QtCore.QtLocationServices',
        'PyQt6.QtCore.QtLocationPermission',
        'PyQt6.QtCore.QtLocationPermissionRequest',
        'PyQt6.QtCore.QtLocationPermissionStatus',
        'PyQt6.QtCore.QtLocationPermissionType',
        'PyQt6.QtCore.QtLocationPermissionScope',
        'PyQt6.QtCore.QtLocationPermissionAccuracy',
        'PyQt6.QtCore.QtLocationPermissionWhenInUse',
        'PyQt6.QtCore.QtLocationPermissionAlways',
        'PyQt6.QtCore.QtLocationPermissionNever',
        'PyQt6.QtCore.QtLocationPermissionDenied',
        'PyQt6.QtCore.QtLocationPermissionGranted',
        'PyQt6.QtCore.QtLocationPermissionRestricted',
        'PyQt6.QtCore.QtLocationPermissionProvisional',
        'PyQt6.QtCore.QtLocationPermissionEphemeral',
        'PyQt6.QtCore.QtLocationPermissionUnspecified',
        'PyQt6.QtCore.QtLocationPermissionUnknown',
        'PyQt6.QtCore.QtLocationPermissionNotDetermined',
        'PyQt6.QtCore.QtLocationPermissionAuthorized',
        'PyQt6.QtCore.QtLocationPermissionAuthorizedAlways',
        'PyQt6.QtCore.QtLocationPermissionAuthorizedWhenInUse',
        'PyQt6.QtCore.QtLocationPermissionDenied',
        'PyQt6.QtCore.QtLocationPermissionRestricted',
        'PyQt6.QtCore.QtLocationPermissionNotDetermined',
        'PyQt6.QtCore.QtLocationPermissionUnknown',
        'PyQt6.QtCore.QtLocationPermissionUnspecified',
        'PyQt6.QtCore.QtLocationPermissionEphemeral',
        'PyQt6.QtCore.QtLocationPermissionProvisional',
        'PyQt6.QtCore.QtLocationPermissionGranted',
        'PyQt6.QtCore.QtLocationPermissionNever',
        'PyQt6.QtCore.QtLocationPermissionAlways',
        'PyQt6.QtCore.QtLocationPermissionWhenInUse',
        'PyQt6.QtCore.QtLocationPermissionAccuracy',
        'PyQt6.QtCore.QtLocationPermissionScope',
        'PyQt6.QtCore.QtLocationPermissionType',
        'PyQt6.QtCore.QtLocationPermissionStatus',
        'PyQt6.QtCore.QtLocationPermissionRequest',
        'PyQt6.QtCore.QtLocationServices',
        'PyQt6.QtCore.QtPositioning',
        'PyQt6.QtCore.QtLocation',
        # Exclude Qt location plugins and modules
        'qtlocation',
        'qtpositioning',
        'qdarwinpermissionplugin_location',
        'qdarwinpermissionplugin_location.mm',
        'QtLocation',
        'QtPositioning',
        'QtLocationServices',
        'QtLocationPermission',
        'QtLocationPermissionRequest',
        'QtLocationPermissionStatus',
        'QtLocationPermissionType',
        'QtLocationPermissionScope',
        'QtLocationPermissionAccuracy',
        'QtLocationPermissionWhenInUse',
        'QtLocationPermissionAlways',
        'QtLocationPermissionNever',
        'QtLocationPermissionDenied',
        'QtLocationPermissionGranted',
        'QtLocationPermissionRestricted',
        'QtLocationPermissionProvisional',
        'QtLocationPermissionEphemeral',
        'QtLocationPermissionUnspecified',
        'QtLocationPermissionUnknown',
        'QtLocationPermissionNotDetermined',
        'QtLocationPermissionAuthorized',
        'QtLocationPermissionAuthorizedAlways',
        'QtLocationPermissionAuthorizedWhenInUse',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Truely',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # Set to False for GUI app (no console window)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Truely',
)

# Create the .app bundle
app = BUNDLE(
    coll,
    name='Truely.app',
    icon=None,  # You can add an icon file here if you have one
    bundle_identifier='com.truely.app',
    info_plist={
        'CFBundleName': 'Truely',
        'CFBundleDisplayName': 'Truely',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHighResolutionCapable': True,
        'LSBackgroundOnly': False,
        'NSRequiresAquaSystemAppearance': False,
        'NSAppTransportSecurity': {
            'NSAllowsArbitraryLoads': True,
        },
        'LSMinimumSystemVersion': '10.13.0',
        'CFBundleDocumentTypes': [],
        'CFBundleURLTypes': [],
        'NSPrincipalClass': 'NSApplication',
        # Add environment variables to Info.plist to disable location services
        'LSEnvironment': {
            'QT_DISABLE_LOCATION': '1',
            'QT_DISABLE_POSITIONING': '1',
            'QT_DISABLE_LOCATION_SERVICES': '1',
            'QT_DISABLE_LOCATION_PERMISSION': '1',
            'QT_DISABLE_LOCATION_PERMISSION_REQUEST': '1',
            'QT_DISABLE_LOCATION_PERMISSION_STATUS': '1',
            'QT_DISABLE_LOCATION_PERMISSION_TYPE': '1',
            'QT_DISABLE_LOCATION_PERMISSION_SCOPE': '1',
            'QT_DISABLE_LOCATION_PERMISSION_ACCURACY': '1',
            'QT_DISABLE_LOCATION_PERMISSION_WHEN_IN_USE': '1',
            'QT_DISABLE_LOCATION_PERMISSION_ALWAYS': '1',
            'QT_DISABLE_LOCATION_PERMISSION_NEVER': '1',
            'QT_DISABLE_LOCATION_PERMISSION_DENIED': '1',
            'QT_DISABLE_LOCATION_PERMISSION_GRANTED': '1',
            'QT_DISABLE_LOCATION_PERMISSION_RESTRICTED': '1',
            'QT_DISABLE_LOCATION_PERMISSION_PROVISIONAL': '1',
            'QT_DISABLE_LOCATION_PERMISSION_EPHEMERAL': '1',
            'QT_DISABLE_LOCATION_PERMISSION_UNSPECIFIED': '1',
            'QT_DISABLE_LOCATION_PERMISSION_UNKNOWN': '1',
            'QT_DISABLE_LOCATION_PERMISSION_NOT_DETERMINED': '1',
            'QT_DISABLE_LOCATION_PERMISSION_AUTHORIZED': '1',
            'QT_DISABLE_LOCATION_PERMISSION_AUTHORIZED_ALWAYS': '1',
            'QT_DISABLE_LOCATION_PERMISSION_AUTHORIZED_WHEN_IN_USE': '1',
            'QT_LOGGING_RULES': 'qt.qpa.*=false',
            'QT_ENABLE_GLYPH_CACHE_WORKAROUND': '1',
            'QT_MAC_WANTS_LAYER': '1',
            'QT_MAC_DISABLE_GLYPH_CACHE_FORCE_32BIT': '1',
            'QT_DISABLE_ACCESSIBILITY': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_REQUEST': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_STATUS': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_TYPE': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_SCOPE': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_ACCURACY': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_WHEN_IN_USE': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_ALWAYS': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_NEVER': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_DENIED': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_GRANTED': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_RESTRICTED': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_PROVISIONAL': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_EPHEMERAL': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_UNSPECIFIED': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_UNKNOWN': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_NOT_DETERMINED': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_AUTHORIZED': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_AUTHORIZED_ALWAYS': '1',
            'QT_DISABLE_ACCESSIBILITY_PERMISSION_AUTHORIZED_WHEN_IN_USE': '1',
        },
        'NSLocationWhenInUseUsageDescription': 'This app does not use location services',
        'NSLocationAlwaysAndWhenInUseUsageDescription': 'This app does not use location services',
        'NSLocationAlwaysUsageDescription': 'This app does not use location services',
        'NSLocationTemporaryUsageDescriptionDictionary': {
            'PurposeKey': 'This app does not use location services'
        },
        'NSLocationUsageDescription': 'This app does not use location services',
        'NSLocationUsageDescriptionDictionary': {
            'PurposeKey': 'This app does not use location services'
        },
        'NSLocationUsageDescriptionKey': 'This app does not use location services',
        'NSLocationUsageDescriptionString': 'This app does not use location services',
        'NSLocationUsageDescriptionText': 'This app does not use location services',
        'NSLocationUsageDescriptionValue': 'This app does not use location services',
        'NSLocationUsageDescriptionData': 'This app does not use location services',
        'NSLocationUsageDescriptionInfo': 'This app does not use location services',
        'NSLocationUsageDescriptionMeta': 'This app does not use location services',
        'NSLocationUsageDescriptionUser': 'This app does not use location services',
        'NSLocationUsageDescriptionSystem': 'This app does not use location services',
        'NSLocationUsageDescriptionNetwork': 'This app does not use location services',
        'NSLocationUsageDescriptionHardware': 'This app does not use location services',
        'NSLocationUsageDescriptionSoftware': 'This app does not use location services',
        'NSLocationUsageDescriptionFirmware': 'This app does not use location services',
        'NSLocationUsageDescriptionDriver': 'This app does not use location services',
        'NSLocationUsageDescriptionLibrary': 'This app does not use location services',
        'NSLocationUsageDescriptionFramework': 'This app does not use location services',
        'NSLocationUsageDescriptionBundle': 'This app does not use location services',
        'NSLocationUsageDescriptionPlugin': 'This app does not use location services',
        'NSLocationUsageDescriptionExtension': 'This app does not use location services',
        'NSLocationUsageDescriptionApp': 'This app does not use location services',
        'NSLocationUsageDescriptionService': 'This app does not use location services',
        'NSLocationUsageDescriptionAgent': 'This app does not use location services',
        'NSLocationUsageDescriptionDaemon': 'This app does not use location services',
        'NSLocationUsageDescriptionProcess': 'This app does not use location services',
        'NSLocationUsageDescriptionThread': 'This app does not use location services',
        'NSLocationUsageDescriptionTask': 'This app does not use location services',
        'NSLocationUsageDescriptionJob': 'This app does not use location services',
        'NSLocationUsageDescriptionSession': 'This app does not use location services',
        'NSLocationUsageDescriptionConnection': 'This app does not use location services',
        'NSLocationUsageDescriptionChannel': 'This app does not use location services',
        'NSLocationUsageDescriptionStream': 'This app does not use location services',
        'NSLocationUsageDescriptionPipe': 'This app does not use location services',
        'NSLocationUsageDescriptionSocket': 'This app does not use location services',
        'NSLocationUsageDescriptionPort': 'This app does not use location services',
        'NSLocationUsageDescriptionEndpoint': 'This app does not use location services',
        'NSLocationUsageDescriptionInterface': 'This app does not use location services',
        'NSLocationUsageDescriptionProtocol': 'This app does not use location services',
        'NSLocationUsageDescriptionAPI': 'This app does not use location services',
        'NSLocationUsageDescriptionSDK': 'This app does not use location services',
        'NSLocationUsageDescriptionToolkit': 'This app does not use location services',
        'NSLocationUsageDescriptionKit': 'This app does not use location services',
        'NSLocationUsageDescriptionCore': 'This app does not use location services',
        'NSLocationUsageDescriptionBase': 'This app does not use location services',
        'NSLocationUsageDescriptionFoundation': 'This app does not use location services',
    },
) 